### ISSUE TITLE
ImportError: No module named 'LCTM.IoU_metrics'

### ISSUE THREAD

**Issue by yangchihyuan** [colincsl/TemporalConvolutionalNetworks#2]
Can anybody tell me, why is there an error?
While I run the TCN_main.py, an error arises.
Traceback (most recent call last):
  File "TCN_main.py", line 40, in <module>
    import tf_models, datasets, utils, metrics
  File "/home/yangchihyuan/Research/TCN/code/metrics.py", line 8, in <module>
    from LCTM.IoU_metrics import *
ImportError: No module named 'LCTM.IoU_metrics'

The LCTM module was downloaded from the GitHub and I installed it using sudo -H python3 setup.py install

I checked the installation by
>>> import LCTM
>>> dir(LCTM)
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']

Where is the IoU_metrics?

**Comment by colincsl** [comment]
Sorry about this! I fixed the issue in the metrics file. I just checked and the file should run with this change: cccdf86

**Comment by yangchihyuan** [comment]
Thank you very much.

**Comment by yangchihyuan** [comment]
In the new metrics.py file, there is no attribute 'ComputeMetrics' and it causes an error on line 84 of the TCN_main.py

> /home/yangchihyuan/Research/TCN/code/TCN_main.py(84)<module>()->None
-> trial_metrics = metrics.ComputeMetrics(overlap=.1, bg_class=bg_class)
(Pdb) n
AttributeError: module 'metrics' has no attribute 'ComputeMetrics'
> <string>(1)<module>()->None
